apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-secret-vulnerable-laravel-devsecops-pipeline-staging
  namespace: staging
spec:
  secretStoreRef:
    name: vault-secret-store-staging
    kind: SecretStore
  target:
    name: secret-vulnerable-laravel-devsecops-pipeline-staging
  refreshInterval: 1m
  data:
    - secretKey: DB_HOST
      remoteRef:
        key: data/vulnerable-laravel-devsecops-pipeline-staging
        property: DB_HOST
    - secretKey: DB_PORT
      remoteRef:
        key: data/vulnerable-laravel-devsecops-pipeline-staging
        property: DB_PORT
    - secretKey: DB_USERNAME
      remoteRef:
        key: data/vulnerable-laravel-devsecops-pipeline-staging
        property: DB_USERNAME
    - secretKey: LOG_CHANNEL
      remoteRef:
        key: data/vulnerable-laravel-devsecops-pipeline-staging
        property: LOG_CHANNEL
    - secretKey: DB_PASSWORD
      remoteRef:
        key: data/vulnerable-laravel-devsecops-pipeline-staging
        property: DB_PASSWORD
    - secretKey: DB_DATABASE
      remoteRef:
        key: data/vulnerable-laravel-devsecops-pipeline-staging
        property: DB_DATABASE
    - secretKey: DB_CONNECTION
      remoteRef:
        key: data/vulnerable-laravel-devsecops-pipeline-staging
        property: DB_CONNECTION
    - secretKey: APP_KEY
      remoteRef:
        key: data/vulnerable-laravel-devsecops-pipeline-staging
        property: APP_KEY
    - secretKey: APP_ENV
      remoteRef:
        key: data/vulnerable-laravel-devsecops-pipeline-staging
        property: APP_ENV