apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store-staging
  namespace: staging
spec:
  provider:
    vault:
      server: "https://vault.infra.karuhun.cloud"
      path: "data"
      auth:
        tokenSecretRef:
          name: vault-token-staging
          key: token
